Sprint 8 solution time and duration
KatyaKosnova/java-kanban pull request #24
Opened 2024-10-08 16:26 UTC by KatyaKosnova

2024-10-08 19:22 UTC, EugeneLenkevich requested changes
Привет, Катя

Что то не то с ПРом (Pull request), в нем очень много изменений, в том числе c предыдущих заданий
Заглянул в репозиторий, ага, все ведется в одной ветке, добавляются только тэги

![image](https://github.com/user-attachments/assets/e37fd6d2-cdbf-4c85-b8eb-ec4a6ac4caa0)

По флоу мы после ревью мержим ветку, в которой вели разработку, в main, ветку удаляем. Далее, для новой доработки, отводим новую ветку от main, вносим правки и создаем новый ПР, который уже будет содержать только последние правки а не все предыдущие. Закомить, пожалуйста, все предыдущие доработки в main и создай ветку только с изменениями по последнему заданию, а то сейчас в ПР-е вообще все изменения с самого начала наверно :)

Потом мы увидим примерно вот такое, тут можно увидеть что у нас было несколько веток и как они мержились в main (по комментариям)

![image](https://github.com/user-attachments/assets/ee8b4888-74c7-429e-b4f8-366e5fa400ac)

2024-10-09 03:49 UTC, EugeneLenkevich requested changes
Привет, мы это добьем :)
Посмотри в ПР, в нем куча изменений с прошлых заданий. Это все должно быть в main тогда тут, в фича-ветке sprint_8-solution-time-and-duration останутся только изменения для 8ого задания, сейчас же в ПРе например вот это, явно с прошлых заданий 

![image](https://github.com/user-attachments/assets/b816a982-841c-41fb-860c-0185de705543)

2024-10-09 08:08 UTC, EugeneLenkevich commented
А у тебя еще ветка sprint_7-solution-in-file-manager локально осталась? Вижу что в репозитории она удалена, если осталась то залей ее и сделай для нее ПР, дальше посмотрим что у нас именно не так идет

2024-10-09 12:16 UTC, KatyaKosnova commented
Здравствуйте! Я когда пыталась с ветками разобраться еще в первый раз, замержила ветки main и sprint_7-solution-in-file-manager.:(

  
>Среда, 9 октября 2024, 13:09 +05:00 от EugeneLenkevich ***@***.***>:
> 
> 
>А у тебя еще ветка sprint_7-solution-in-file-manager локально осталась? Вижу что в репозитории она удалена, если осталась то залей ее и сделай для нее ПР, дальше посмотрим что у нас именно не так идет
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <KatyaKosnova/java-kanban/pull/24/c2401635667 @ github . com> 
 
 
--
Katya Kosnova
Отправлено из Почты  Mail
 

2024-10-09 12:32 UTC, EugeneLenkevich commented
> Здравствуйте! Я когда пыталась с ветками разобраться еще в первый раз, замержила ветки main и sprint_7-solution-in-file-manager.:(  

Смотрю в ветке main вроде все есть, а почему тогда в ПР отображаются эти изменения... что то необычное твориться, давай, вот, например, изменения, которые будь то бы не относятся к задаче, ты с этими файлами ничего не делала?
В общем шли назад работу, попробуем дальше разобраться 

![image](https://github.com/user-attachments/assets/2c5434c5-6817-4b7f-931a-d71c44fea6c3)

2024-10-09 18:14 UTC, EugeneLenkevich approved these changes
Ок, в целом это задание такое, проходное, давай теперь закроем этот ПР и для спокойствия убедимся чтобы все изменения попали в main и в следующем ПР-е будут только те изменения, которые относятся к текущему (будущему) заданию :)

2024-10-10 10:26 UTC, merged

2024-10-10 10:28 UTC, KatyaKosnova commented
Добрый день! Так это должно выглядеть ? 

  
>Среда, 9 октября 2024, 23:15 +05:00 от EugeneLenkevich ***@***.***>:
> 
> 
>@EugeneLenkevich approved this pull request.
>Ок, в целом это задание такое, проходное, давай теперь закроем этот ПР и для спокойствия убедимся чтобы все изменения попали в main и в следующем ПР-е будут только те изменения, которые относятся к текущему (будущему) заданию :)
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <KatyaKosnova/java-kanban/pull/24/review/2357862606 @ github . com> 
 
 
--
Katya Kosnova
Отправлено из Почты  Mail
 

2024-10-10 10:38 UTC, EugeneLenkevich commented
> Добрый день! Так это должно выглядеть ?   

Ветки смержены, отметка в ПР есть и комит в истории присутствует, все верно. Все, дальше, для следующего задания, следующую фича-ветку делаем от main :)


![image](https://github.com/user-attachments/assets/00f26dd3-ff1d-4fdf-b1d8-2ef84e76311e)

![image](https://github.com/user-attachments/assets/b807cf39-c105-40bc-91dc-598de74434bc)